-- Crear tabla de Clientes (CRM)
CREATE TABLE IF NOT EXISTS public.clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custom_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    tax_id TEXT,
    email TEXT,
    address TEXT,
    phone TEXT,
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Crear tabla de Facturas/Proformas
CREATE TABLE IF NOT EXISTS public.invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custom_id TEXT UNIQUE NOT NULL,
    client_id TEXT NOT NULL REFERENCES public.clients(custom_id) ON DELETE CASCADE,
    type TEXT NOT NULL, -- 'Factura', 'Proforma', 'Albarán'
    date DATE NOT NULL,
    language TEXT DEFAULT 'es',
    total_amount DECIMAL(10,2) DEFAULT 0.00,
    status TEXT DEFAULT 'Emitida',
    items JSONB DEFAULT '[]'::jsonb, -- Guardará los lotes vendidos, cantidad y precio
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS (Seguridad a Nivel de Fila)
ALTER TABLE public.clients ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

-- Políticas básicas (Permitir lectura/escritura a usuarios autenticados)
-- Nota: Puedes ajustar esto a roles específicos (ej: solo 'Admin') más adelante.
CREATE POLICY "Enable all access for authenticated users on clients" 
ON public.clients FOR ALL TO authenticated USING (true);

CREATE POLICY "Enable all access for authenticated users on invoices" 
ON public.invoices FOR ALL TO authenticated USING (true);
